services:
  frontend:
    build: ./my-project
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://3.237.34.111:3000
    depends_on:
      - backend
    restart: always
  backend:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRETKEY=chintapaktamtam
      - MONGO_URI=mongodb+srv://ecommerce:ecommerce123@ecommerce.85s1apq.mongodb.net/?retryWrites=true&w=majority&appName=ecommerce
    restart: always
